spring.application.name=departmentservice
server.port=8082

# MySQL (schema auto-created on first run)
spring.datasource.url=jdbc:mysql://localhost:3306/department_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Register with the Eureka registry running on 8761
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
