spring.application.name=employeeservice
server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/employee_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwt.secret=change-this-demo-secret-key-please-32bytes-min-fdp-klu
app.jwt.expiration-ms=3600000